## Q4: The Biased History Experiment


In [1]:
# Import Statements
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.metrics import confusion_matrix, accuracy_score, mean_squared_error
import seaborn as sns

In [7]:
# Create a simple synthetic dataset representing company employees
experience = [1,2,3,4,5,1,2,3,4,5]
group = [0,0,0,0,0,1,1,1,1,1]

# 6 years test
experience_6 = [1,2,3,4,5,6,1,2,3,4,5,6]
group_6 = [0,0,0,0,0,0,1,1,1,1,1,1]

salary = []
for exp, grp in zip(experience, group):
  base = exp * 2000
  if grp == 1:
    base = base + 10000
  salary.append(base)

print("Experience:")
print(experience)

print("Group:")
print(group)

print("Salary:")
print(salary)

Experience:
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Group:
[0, 0, 0, 0, 0, 1, 1, 1, 1, 1]
Salary:
[2000, 4000, 6000, 8000, 10000, 12000, 14000, 16000, 18000, 20000]


In [8]:
# Train the Model
X = np.column_stack((experience, group))
print(X)

X_6 = np.column_stack((experience_6, group_6))
print(X_6)

[[1 0]
 [2 0]
 [3 0]
 [4 0]
 [5 0]
 [1 1]
 [2 1]
 [3 1]
 [4 1]
 [5 1]]
[[1 0]
 [2 0]
 [3 0]
 [4 0]
 [5 0]
 [6 0]
 [1 1]
 [2 1]
 [3 1]
 [4 1]
 [5 1]
 [6 1]]


In [9]:
print("Training Model...")
model = LinearRegression()
model.fit(X, salary)
y_pred = model.predict(X)
y_pred_6 = model.predict(X_6) # predicton with 6exp included
print("Model trained.")
print("-" * 30)

Training Model...
Model trained.
------------------------------


In [11]:
print(y_pred) # salary prediction
print("Six Years Included Prediction:")
print(y_pred_6) # salary prediction w/ 6exp

[ 2000.  4000.  6000.  8000. 10000. 12000. 14000. 16000. 18000. 20000.]
Six Years Included Prediction:
[ 2000.  4000.  6000.  8000. 10000. 12000. 12000. 14000. 16000. 18000.
 20000. 22000.]
